kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      labels:
        name: deployment
    spec:
      containers:
        - name: finance-cont
          image: adityagujjar/project-finance:V1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081                           
